import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      process: 'Process',
      portfolio: 'Portfolio',
      journey: 'Journey',
      services: 'Services',
      contact: 'Contact',
      hireMe: 'Get In Touch',
      langToggle: 'VI',
    },
    hero: {
      badge: 'Available for Product & UI/UX Roles',
      greeting: "Hello, I'm",
      name: 'Nguyen Xuan Hau',
      title: 'Product / UIUX Designer with a Business Analysis Background',
      subtitle: 'I turn complex business requirements, workflows and system logic into clear, usable digital products across Web, Mobile and Admin platforms.',
      sayHello: 'Say Hello',
      viewPortfolio: 'View Portfolio',
      specialty: 'Specialty',
      specialtyTitle: 'BA & Product Design',
      stats: [
        { value: 'BA → UX', label: 'Requirements to UI' },
        { value: '7 Projects', label: 'End-to-End Systems' },
        { value: 'Web · Mobile', label: 'Multi-Platform' },
      ],
    },
    about: {
      badge: 'About Me',
      role: 'Business Analyst & UIUX Designer focused on complex systems',
      bio: 'Business Analyst and UIUX Designer focused on complex systems. I started in Business Analysis before moving deeper into UIUX. That foundation helps me clarify requirements, business rules, roles, states and edge cases before translating them into product flows and interfaces.',
      myProjects: 'My Projects',
      downloadCv: 'Download CV',
      cvNote: 'PDF available on request',
    },
    process: {
      badge: 'Process',
      title: 'Work Process',
      subtitle: 'Every project follows an agile and human-centered design framework. I combine rigorous business analysis with rapid prototyping and system UX design.',
      learnMore: 'Learn more about our methodology →',
      steps: [
        {
          step: '01',
          title: '1. Understand Requirements',
          description: 'Deep dive into stakeholder goals, product discovery, and user needs to lay a solid foundation.',
        },
        {
          step: '02',
          title: '2. Analyze Business Logic',
          description: 'Synthesize requirements, business rules, entity models, and domain constraints.',
        },
        {
          step: '03',
          title: '3. Roles, Rules & States',
          description: 'Define RBAC permissions, validation rules, error handling, and comprehensive system states.',
        },
        {
          step: '04',
          title: '4. Flow & IA',
          description: 'Build user journeys, information architecture, navigation hierarchy, and cross-system workflows.',
        },
        {
          step: '05',
          title: '5. UI & Interaction',
          description: 'Craft high-fidelity interfaces, atomic design systems, and responsive layouts with pixel precision.',
        },
        {
          step: '06',
          title: '6. Prototype & Validate',
          description: 'Build interactive prototypes to stress-test real workflows, edge cases, and transaction paths.',
        },
        {
          step: '07',
          title: '7. Design QA',
          description: 'Audit layouts across breakpoints (1440px to 390px), ensuring design parity and accessibility.',
        },
        {
          step: '08',
          title: '8. Developer Handoff',
          description: 'Deliver structured Figma tokens, components, state specs, and support engineers during build.',
        },
      ],
    },
    portfolio: {
      badge: 'Portfolio',
      title: 'Featured Projects',
      subtitle: 'Explore 7 digital products spanning Vertical SaaS, travel booking, internal inventory operations, and omnichannel ticketing.',
      all: 'All',
      viewCaseStudy: 'View Case Study',
      seeCaseStudy: 'See Case Study',
      moreWork: 'View All Projects',
      client: 'Domain',
      year: 'Year',
      role: 'Role',
      platforms: 'Platforms',
      deliverables: 'Key Deliverables & System Logic',
      discussProject: 'Discuss Similar Project',
      close: 'Close',
      zoomIn: 'Click to expand image',
      closeZoom: 'Close full view',
      imageCounter: 'Screen',
      of: 'of',
      caseStudyNumber: 'Case Study',
      coreSkills: 'Core Design Skills & Domain',
      systemLogicTitle: 'System Logic & Architecture Highlights',
      modulesTitle: 'Operational Modules',
      modulesUnit: 'Modules',
      categories: {
        'All': 'All',
        'Vertical SaaS': 'Vertical SaaS',
        'Travel & Booking': 'Travel & Booking',
        'Internal Operations': 'Internal Operations',
        'Hybrid BA + UX': 'Hybrid BA + UX',
      },
    },
    cta: {
      badge: 'Product Design & System Strategy',
      title: 'Complex products need clear thinking.',
      titleHighlight: "Let's build impactful software together!",
      subtitle: 'I combine Business Analysis and Product Design to translate complex workflows, rules and system constraints into usable product experiences.',
      button: 'See My Process',
    },
    journey: {
      badge: 'CAREER JOURNEY',
      title: 'Career Journey',
      subtitle: 'Technical data foundation → Business Analysis → System Analysis → Product & UI/UX Design.',
      currentRoleTag: 'Current Role',
      items: [
        {
          yearBadge: '2023',
          stage: 'TECHNICAL DATA FOUNDATION',
          company: 'HPT Vietnam Corporation',
          role: 'Database Admin & Data Engineer Intern',
          period: '06/2023 – 09/2023',
          description: 'Built fundamentals in data structures, SQL queries, and backend technical constraints.',
          icon: 'Database',
          isCurrent: false,
        },
        {
          yearBadge: '2024–2025',
          stage: 'BUSINESS ANALYSIS FOUNDATION',
          company: 'IS Group',
          role: 'Business Analyst',
          period: '07/2024 – 02/2025',
          description: 'Analyzed customer requirements, mapped business rules, and authored functional specification documents.',
          icon: 'TrendingUp',
          isCurrent: false,
        },
        {
          yearBadge: '2025–2026',
          stage: 'SYSTEM & BUSINESS ANALYSIS',
          company: 'DOTB',
          role: 'Business Analyst — EdTech',
          period: '10/2025 – 01/2026',
          description: 'Analyzed EdTech product systems: commercial business rules, user permission matrix, validation, and operational flows.',
          icon: 'Cpu',
          isCurrent: false,
        },
        {
          yearBadge: '2026 – Present',
          stage: 'PRODUCT & UI/UX DESIGN',
          company: 'Techera',
          role: 'UIUX Designer / Product Designer',
          period: '02/2026 – Present',
          description: 'Leading product experience design: Information Architecture, multi-role SaaS, responsive web, native mobile, and Design QA.',
          icon: 'Sparkles',
          isCurrent: true,
        },
      ],
    },
    services: {
      badge: 'Value & Skills',
      title: 'What I Bring to a Product Team',
      subtitle: 'From complex business rules and state modeling to high-fidelity design systems and production handoff.',
      intro: 'I bridge the gap between business logic, system analysis, and high-fidelity interface design to ensure smooth engineering execution.',
      sayHello: 'Discuss Collaboration',
      items: [
        {
          id: 'product-ux',
          title: 'Product & UX Design',
          description: 'Crafting end-to-end product architecture and interaction models for complex B2C, B2B and SaaS platforms.',
          skills: [
            'Information Architecture (IA)',
            'User Flows & Journey Mapping',
            'Interaction Design',
            'Responsive Design (Desktop/Tablet/Mobile)',
            'System UX & Status Modeling',
            'Design QA & Visual Auditing',
          ],
        },
        {
          id: 'business-analysis',
          title: 'Business Analysis',
          description: 'Leveraging a solid BA background to clarify business logic, rules, validation, and permissions before designing.',
          skills: [
            'Requirement Analysis & Clarification',
            'Business Rules & Constraints',
            'Feature Breakdown & Scoping',
            'Roles & RBAC Permissions',
            'Form Validation & Error Modeling',
            'System States & Edge Cases',
          ],
        },
        {
          id: 'design-execution',
          title: 'Design Execution & AI Workflows',
          description: 'Building scalable design systems, production-ready prototypes, and accelerating discovery with AI tools.',
          skills: [
            'Figma Design Systems & Variables',
            'Atomic Reusable Components',
            'Interactive High-Fidelity Prototypes',
            'Developer Handoff Documentation',
            'AI-assisted Requirement Analysis',
            'Edge-Case & Prompt Exploration',
          ],
        },
      ],
    },
    contact: {
      badge: 'Get in Touch',
      title: "Let's build clearer digital products.",
      subtitle: "I'm open to Junior UIUX Designer, Product Designer and product-oriented UIUX opportunities.",
      addressTitle: 'Location',
      addressValue: 'Ho Chi Minh City, Vietnam',
      emailTitle: 'Email',
      phoneTitle: 'Phone Number',
      phoneValue: 'Available upon request / Zalo',
      phoneNote: 'Ready for direct call or Zalo discussion',
      cvDownloadsTitle: 'Download Specialized Resumes (CV)',
      cvDownloadsSubtitle: 'Select and download the resume version suited to your role requirements',
      cvPdfsReady: '3 PDF Tracks Ready',
      downloadPdf: 'Download PDF',
      budgetOption1: 'Full-time Employment',
      budgetOption2: 'Contract / Freelance Project',
      budgetOption3: 'Design System & QA Consulting',
      budgetOption4: 'Other Inquiries',
      cvList: [
        {
          id: 'uiux',
          role: 'UI/UX & Product Designer',
          specialty: 'Product Design, Design System, Complex Workflows',
          fileName: 'Nguyen_Xuan_Hau_CV_UIUX_Designer.pdf',
          badge: 'Design Track',
        },
        {
          id: 'ba',
          role: 'Business Analyst (BA)',
          specialty: 'Requirements, System Rules, RBAC & Data Logic',
          fileName: 'Nguyen_Xuan_Hau_CV_Business_Analyst.pdf',
          badge: 'BA Track',
        },
        {
          id: 'tech',
          role: 'Computer Engineering & Tech',
          specialty: 'Database Architecture, SQL Queries, Tech Fundamentals',
          fileName: 'Nguyen_Xuan_Hau_CV_Computer_Engineering.pdf',
          badge: 'Tech Track',
        },
      ],
      followMe: 'Connect with me',
      yourName: 'Your Name *',
      yourEmail: 'Your Email *',
      subject: 'Discussion Topic',
      budget: 'Opportunity Type',
      message: 'Your Message *',
      send: 'Send Message',
      sending: 'Sending message...',
      successTitle: 'Message Sent Successfully!',
      successDesc: "Thank you for reaching out. I'll review your inquiry and respond within 24 hours.",
    },
    footer: {
      rights: 'All rights reserved.',
    },
  },
  vi: {
    nav: {
      home: 'Trang chủ',
      about: 'Giới thiệu',
      process: 'Quy trình',
      portfolio: 'Dự án',
      journey: 'Hành trình',
      services: 'Kỹ năng',
      contact: 'Liên hệ',
      hireMe: 'Liên hệ ngay',
      langToggle: 'EN',
    },
    hero: {
      badge: 'Sẵn sàng cho các vị trí Product & UI/UX Designer',
      greeting: 'Xin chào, tôi là',
      name: 'Nguyễn Xuân Hậu',
      title: 'Product / UIUX Designer với nền tảng Business Analysis',
      subtitle: 'Tôi chuyển hóa các yêu cầu nghiệp vụ, luồng quy trình và logic hệ thống phức tạp thành các sản phẩm số rõ ràng, trực quan và dễ sử dụng trên Web, Mobile và Admin.',
      sayHello: 'Liên hệ ngay',
      viewPortfolio: 'Xem dự án',
      specialty: 'Chuyên môn',
      specialtyTitle: 'Thiết kế BA & UX',
      stats: [
        { value: 'BA → UX', label: 'Nghiệp vụ đến UI' },
        { value: '7 Dự án', label: 'Sản phẩm thực tế' },
        { value: 'Web · Mobile', label: 'Đa nền tảng' },
      ],
    },
    about: {
      badge: 'Giới thiệu',
      role: 'Chuyên viên Phân tích Nghiệp vụ & Thiết kế UIUX tập trung vào các hệ thống phức tạp',
      bio: 'Chuyên viên Phân tích Nghiệp vụ (BA) và Thiết kế UIUX tập trung vào các hệ thống phức tạp. Tôi khởi đầu từ Business Analysis trước khi chuyển sâu vào UIUX. Nền tảng phân tích giúp tôi làm rõ yêu cầu, quy tắc nghiệp vụ, phân quyền vai trò, trạng thái hệ thống và các trường hợp ngoại lệ trước khi chuyển đổi thành luồng sản phẩm và giao diện.',
      myProjects: 'Xem dự án',
      downloadCv: 'Tải CV (PDF)',
      cvNote: 'Sẵn sàng gửi PDF khi có yêu cầu',
    },
    process: {
      badge: 'Quy trình',
      title: 'Quy Trình Làm Việc',
      subtitle: 'Mỗi dự án đều tuân theo khung thiết kế lấy con người làm trung tâm, kết hợp chặt chẽ giữa phân tích nghiệp vụ, kiến trúc thông tin và thiết kế giao diện.',
      learnMore: 'Tìm hiểu thêm về phương pháp luận →',
      steps: [
        {
          step: '01',
          title: '1. Thấu hiểu yêu cầu',
          description: 'Nghiên cứu mục tiêu kinh doanh, phân tích bối cảnh bài toán và nhu cầu người dùng làm nền móng vững chắc.',
        },
        {
          step: '02',
          title: '2. Phân tích logic nghiệp vụ',
          description: 'Bóc tách quy tắc nghiệp vụ, mô hình thực thể dữ liệu và các ràng buộc hệ thống trước khi vẽ màn hình.',
        },
        {
          step: '03',
          title: '3. Vai trò, quy tắc & trạng thái',
          description: 'Xác định phân quyền vai trò (RBAC), kiểm tra tính hợp lệ dữ liệu, xử lý ngoại lệ và trạng thái tương tác.',
        },
        {
          step: '04',
          title: '4. Xây dựng luồng & IA',
          description: 'Kiến trúc hóa hành trình người dùng, phân cấp điều hướng và luồng xử lý liên hệ thống xuyên suốt.',
        },
        {
          step: '05',
          title: '5. Thiết kế UI & tương tác',
          description: 'Thiết kế giao diện độ nét cao, hệ thống Design System nguyên tử và layout responsive chuẩn xác.',
        },
        {
          step: '06',
          title: '6. Prototype & kiểm thử',
          description: 'Tạo bản mẫu tương tác thực tế để kiểm tra giao dịch, các trường hợp biên và mật độ dữ liệu.',
        },
        {
          step: '07',
          title: '7. Kiểm thử thiết kế (QA)',
          description: 'Đánh giá độ tương thích trên các độ phân giải (1440px đến 390px), đảm bảo chuẩn UX nhất quán.',
        },
        {
          step: '08',
          title: '8. Bàn giao lập trình (Handoff)',
          description: 'Cung cấp Figma tokens, components chuẩn xác, tài liệu chi tiết và đồng hành cùng team Developer.',
        },
      ],
    },
    portfolio: {
      badge: 'Dự án',
      title: 'Dự Án Tiêu Biểu',
      subtitle: 'Khám phá 7 sản phẩm số thực tế trải dài từ Vertical SaaS, cổng đặt vé du lịch, kho vận nội bộ đến hệ sinh thái đa kênh.',
      all: 'Tất cả',
      viewCaseStudy: 'Xem chi tiết',
      seeCaseStudy: 'Xem chi tiết',
      moreWork: 'Xem tất cả 7 dự án',
      client: 'Lĩnh vực',
      year: 'Năm',
      role: 'Vai trò',
      platforms: 'Nền tảng',
      deliverables: 'Hạng mục bàn giao & Logic hệ thống',
      discussProject: 'Thảo luận về dự án này',
      close: 'Đóng',
      zoomIn: 'Bấm để xem ảnh phóng to',
      closeZoom: 'Đóng chế độ phóng to',
      imageCounter: 'Hình',
      of: 'trên',
      caseStudyNumber: 'Hồ sơ dự án',
      coreSkills: 'Lĩnh Vực & Kỹ Năng Thiết Kế Cốt Lõi',
      systemLogicTitle: 'Điểm Sáng Logic Hệ Thống & Kiến Trúc',
      modulesTitle: 'Phân Hệ Chức Năng',
      modulesUnit: 'Phân hệ',
      categories: {
        'All': 'Tất cả',
        'Vertical SaaS': 'Vertical SaaS',
        'Travel & Booking': 'Du lịch & Đặt vé',
        'Internal Operations': 'Vận hành nội bộ',
        'Hybrid BA + UX': 'Kết hợp BA + UX',
      },
    },
    cta: {
      badge: 'Thiết Kế Sản Phẩm & Tư Duy Hệ Thống',
      title: 'Sản phẩm phức tạp cần tư duy rõ ràng.',
      titleHighlight: 'Cùng trao đổi về sản phẩm của bạn!',
      subtitle: 'Tôi kết hợp tư duy Business Analysis và Product Design để chuyển hóa các luồng nghiệp vụ, quy tắc và ràng buộc hệ thống thành trải nghiệm người dùng tối ưu.',
      button: 'Xem quy trình làm việc',
    },
    journey: {
      badge: 'HÀNH TRÌNH SỰ NGHIỆP',
      title: 'Lộ Trình Nghề Nghiệp',
      subtitle: 'Nền tảng kỹ thuật dữ liệu → Business Analysis → Phân tích hệ thống → Thiết kế Sản phẩm & UI/UX.',
      currentRoleTag: 'Vị trí hiện tại',
      items: [
        {
          yearBadge: '2023',
          stage: 'NỀN TẢNG KỸ THUẬT DỮ LIỆU',
          company: 'HPT Vietnam Corporation',
          role: 'Thực tập sinh Quản trị CSDL & Kỹ sư Dữ liệu',
          period: '06/2023 – 09/2023',
          description: 'Xây dựng tư duy cấu trúc dữ liệu, câu lệnh truy vấn và các ràng buộc kỹ thuật của backend.',
          icon: 'Database',
          isCurrent: false,
        },
        {
          yearBadge: '2024–2025',
          stage: 'NỀN TẢNG PHÂN TÍCH NGHIỆP VỤ',
          company: 'IS Group',
          role: 'Business Analyst',
          period: '07/2024 – 02/2025',
          description: 'Phân tích yêu cầu khách hàng, xác định các trường hợp nghiệp vụ và lập tài liệu đặc tả chức năng.',
          icon: 'TrendingUp',
          isCurrent: false,
        },
        {
          yearBadge: '2025–2026',
          stage: 'PHÂN TÍCH HỆ THỐNG & NGHIỆP VỤ',
          company: 'DOTB',
          role: 'Business Analyst — EdTech',
          period: '10/2025 – 01/2026',
          description: 'Phân tích hệ thống sản phẩm giáo dục: quy tắc kinh doanh, phân quyền tài khoản, validation và luồng thao tác.',
          icon: 'Cpu',
          isCurrent: false,
        },
        {
          yearBadge: '2026 – Hiện tại',
          stage: 'THIẾT KẾ SẢN PHẨM & UI/UX',
          company: 'Techera',
          role: 'UIUX Designer / Product Designer',
          period: '02/2026 – Hiện tại',
          description: 'Phụ trách thiết kế trải nghiệm sản phẩm: Kiến trúc thông tin, SaaS đa phân quyền, Responsive Web và Mobile App.',
          icon: 'Sparkles',
          isCurrent: true,
        },
      ],
    },
    services: {
      badge: 'Giá trị & Kỹ năng',
      title: 'Tôi Mang Gì Đến Cho Product Team?',
      subtitle: 'Từ quy tắc nghiệp vụ và mô hình hóa trạng thái đến hệ thống Design System và bàn giao lập trình.',
      intro: 'Tôi giúp kết nối chặt chẽ giữa logic bài toán, phân tích hệ thống và thiết kế giao diện độ nét cao, đảm bảo sản phẩm vận hành mượt mà khi lập trình.',
      sayHello: 'Liên hệ trao đổi',
      items: [
        {
          id: 'product-ux',
          title: 'Thiết Kế Sản Phẩm & Trải Nghiệm UX',
          description: 'Xây dựng kiến trúc sản phẩm toàn diện và mô hình tương tác cho các nền tảng B2C, B2B và SaaS phức tạp.',
          skills: [
            'Kiến trúc Thông tin (IA)',
            'Bản đồ Hành trình & Luồng Thao tác',
            'Thiết kế Tương tác (Interaction Design)',
            'Thiết kế Responsive (Desktop/Tablet/Mobile)',
            'Mô hình hóa Trạng thái Hệ thống',
            'Kiểm thử Giao diện (Design QA)',
          ],
        },
        {
          id: 'business-analysis',
          title: 'Phân Tích Nghiệp Vụ (Business Analysis)',
          description: 'Tận dụng nền tảng BA vững chắc để làm rõ logic bài toán, quy tắc vận hành, validation và phân quyền trước khi thiết kế.',
          skills: [
            'Bóc tách & Làm rõ Yêu cầu Nghiệp vụ',
            'Quy tắc Kinh doanh & Ràng buộc Hệ thống',
            'Phân rã Tính năng & Xác định Phạm vi',
            'Ma trận Vai trò & Phân quyền RBAC',
            'Validation Biểu mẫu & Xử lý Lỗi',
            'Mô hình Trạng thái & Trường hợp Ngoại lệ',
          ],
        },
        {
          id: 'design-execution',
          title: 'Thực Thi Thiết Kế & Ứng Dụng AI',
          description: 'Xây dựng hệ thống Design System chuẩn mực, bản mẫu Prototype chân thực và tăng tốc nghiên cứu bằng công cụ AI.',
          skills: [
            'Figma Design Systems & Variables',
            'Component Tái Sử Dụng Nguyên Tử',
            'Prototype Tương Tác Độ Nét Cao',
            'Tài liệu Bàn Giao Lập Trình (Handoff)',
            'Ứng dụng AI Phân tích Yêu cầu',
            'Khám phá Trường hợp Biên & Prompt Engineering',
          ],
        },
      ],
    },
    contact: {
      badge: 'LIÊN HỆ',
      title: 'Cùng xây dựng các sản phẩm số trực quan hơn.',
      subtitle: 'Tôi sẵn sàng đón nhận cơ hội ở các vị trí Junior UIUX Designer, Product Designer và các dự án thiết kế định hướng sản phẩm.',
      addressTitle: 'ĐỊA ĐIỂM',
      addressValue: 'Thành phố Hồ Chí Minh, Việt Nam',
      emailTitle: 'EMAIL',
      phoneTitle: 'SỐ ĐIỆN THOẠI',
      phoneValue: 'Sẵn sàng kết nối qua SĐT / Zalo',
      phoneNote: 'Sẵn sàng trao đổi trực tiếp',
      cvDownloadsTitle: 'Tải Hồ Sơ Năng Lực (CV)',
      cvDownloadsSubtitle: 'Chọn và tải phiên bản hồ sơ năng lực phù hợp với tiêu chí tuyển dụng của bạn',
      cvPdfsReady: '3 File PDF Sẵn Sàng',
      downloadPdf: 'Tải xuống bản PDF',
      budgetOption1: 'Toàn thời gian (Full-time)',
      budgetOption2: 'Dự án / Hợp đồng (Contract/Freelance)',
      budgetOption3: 'Tư vấn Design System & Kiểm thử QA',
      budgetOption4: 'Trao đổi khác',
      cvList: [
        {
          id: 'uiux',
          role: 'CV UI/UX Designer',
          specialty: 'Thiết kế Sản phẩm, Design System, SaaS Đa Phân Quyền',
          fileName: 'Nguyen_Xuan_Hau_CV_UIUX_Designer.pdf',
          badge: 'Chuyên môn UI/UX',
        },
        {
          id: 'ba',
          role: 'CV Business Analyst (BA)',
          specialty: 'Đặc tả yêu cầu, Logic nghiệp vụ, RBAC, Luồng tương tác',
          fileName: 'Nguyen_Xuan_Hau_CV_Business_Analyst.pdf',
          badge: 'Chuyên môn BA',
        },
        {
          id: 'tech',
          role: 'CV Kỹ thuật Máy tính / IT',
          specialty: 'Kiến trúc CSDL, Truy vấn SQL, Tư duy kỹ thuật hệ thống',
          fileName: 'Nguyen_Xuan_Hau_CV_Computer_Engineering.pdf',
          badge: 'Kỹ thuật & Dữ liệu',
        },
      ],
      followMe: 'KẾT NỐI CÙNG TÔI',
      yourName: 'Họ và tên của bạn *',
      yourEmail: 'Địa chỉ Email *',
      subject: 'Chủ đề trao đổi',
      budget: 'Loại hình cơ hội',
      message: 'Nội dung lời nhắn *',
      send: 'Gửi tin nhắn',
      sending: 'Đang gửi tin nhắn...',
      successTitle: 'Đã gửi tin nhắn thành công!',
      successDesc: 'Cảm ơn bạn đã liên hệ. Tôi sẽ phản hồi lại bạn trong vòng 24 giờ.',
    },
    footer: {
      rights: 'Bảo lưu mọi quyền.',
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('portfolio_lang') || 'vi';
  });

  useEffect(() => {
    localStorage.setItem('portfolio_lang', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'vi' : 'en'));
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
