import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      process: 'Process',
      portfolio: 'Portfolio',
      journey: 'Journey & Process',
      services: 'Services',
      contact: 'Contact',
      hireMe: 'Get In Touch',
      langToggle: 'VI',
    },
    hero: {
      eyebrow: 'BUSINESS ANALYST · UI/UX DESIGNER',
      badge: 'BUSINESS ANALYST · UI/UX DESIGNER',
      greeting: "Hi, I'm",
      name: 'Nguyen Xuan Hau',
      role: 'Business Analyst & UI/UX Designer',
      mainDesc: 'I bridge business requirements and user experience — turning complex workflows, rules and system logic into clear, practical interfaces across Web, Mobile and Admin platforms.',
      personalIntro: 'I started my career in Business Analysis, working with requirements, business flows and system logic before moving deeper into UI/UX. That background shapes how I design today: I prefer to understand how a product works before deciding how it should look and behave.',
      subtitle: 'I bridge business requirements and user experience — turning complex workflows, rules and system logic into clear, practical interfaces across Web, Mobile and Admin platforms.',
      sayHello: 'Say Hello',
      viewPortfolio: 'View Portfolio',
      specialty: 'Specialty',
      specialtyTitle: 'Business Analysis & UI/UX',
      stats: [
        { value: 'BA → UX', label: 'Business logic to interface' },
        { value: '7 Projects', label: 'Real product systems' },
        { value: 'Web · Mobile · Admin', label: 'Multi-platform experience' },
      ],
    },
    about: {
      eyebrow: 'HOW I THINK',
      titlePart1: 'Where Business Logic Becomes',
      titlePart2: 'Product Experience',
      statement: 'My Business Analysis background enables me to evaluate products through requirements, business rules, system states, and edge cases before touching the interface. Transitioning to UI/UX, I leverage that foundation to translate complex system logic into intuitive user flows, clear UI states, and production-ready handoffs.',
      pipeline: {
        tag: 'SYNTHESIS PIPELINE',
        steps: ['Business Requirement', 'Product Logic', 'UX Flow', 'Interface'],
      },
      business: {
        tag: 'INPUT LAYER · SYSTEM THINKING',
        title: 'BUSINESS LOGIC',
        subtitle: 'System foundation & technical constraints',
        items: [
          { num: '01', name: 'Requirement', desc: 'Business goals, user problems & operational scope' },
          { num: '02', name: 'Business Rules', desc: 'Operational constraints, validation logic & trigger conditions' },
          { num: '03', name: 'Roles & Permissions', desc: 'RBAC access matrix, actions & boundary governance' },
          { num: '04', name: 'Fields & Validation', desc: 'Data schema, field dependencies & error rules' },
          { num: '05', name: 'System States', desc: 'Data lifecycle, synchronization & background transitions' },
          { num: '06', name: 'Edge Cases', desc: 'Network timeouts, exception handling & rare failure modes' },
        ],
      },
      bridge: {
        badge: 'BA → UX',
        title: 'BRIDGE',
        steps: [
          { step: '01', name: 'UNDERSTAND', desc: 'Grasp business logic & constraints' },
          { step: '02', name: 'STRUCTURE', desc: 'Organize data models & workflows' },
          { step: '03', name: 'TRANSLATE', desc: 'Shape interfaces & interactions' },
        ],
      },
      experience: {
        tag: 'OUTPUT LAYER · INTERFACE CRAFT',
        title: 'PRODUCT EXPERIENCE',
        subtitle: 'Digital interfaces, interactions & design QA',
        items: [
          { num: '01', name: 'Information Architecture', desc: 'Clear content hierarchy & intuitive navigation maps' },
          { num: '02', name: 'User Flow', desc: 'Frictionless, goal-oriented journeys with zero dead-ends' },
          { num: '03', name: 'Interaction Design', desc: 'Micro-interactions, intuitive feedback & seamless states' },
          { num: '04', name: 'UI States & Feedback', desc: 'Empty, loading, validation, error & success parity' },
          { num: '05', name: 'Responsive Interface', desc: 'Adaptive multi-device parity across Desktop & Mobile' },
          { num: '06', name: 'Design QA', desc: 'Pixel-perfect verification & developer-ready handoff specs' },
        ],
      },
      principlesTitle: 'DESIGN PRINCIPLES',
      principles: [
        {
          num: '01',
          title: 'LOGIC BEFORE PIXELS',
          quote: '“Clarify requirements, rules, and system dependencies before deciding on the interface.”',
        },
        {
          num: '02',
          title: 'DESIGN THE STATE, NOT ONLY THE HAPPY PATH',
          quote: '“Empty, loading, validation, permission, and exception states are all integral parts of the experience.”',
        },
        {
          num: '03',
          title: 'CLARIFY BEFORE ASSUMING',
          quote: '“When requirements are ambiguous, prioritize proactive alignment with BA, PM, Developer, and QA over guesswork.”',
        },
      ],
      beyond: {
        badge: 'BEYOND PRODUCT',
        desc: 'Beyond product design, I explore AI-assisted workflows, computer hardware, 3D printing, and how technical systems operate.',
        tags: ['AI-assisted Workflow', '3D Printing', 'Hardware', 'New Technology'],
      },
      // Fallbacks
      badge: 'HOW I THINK',
      role: 'Where Business Logic Becomes Product Experience',
    },
    process: {
      badge: 'Process',
      title: 'Work Process',
      subtitle: 'Every project follows an agile and human-centered design framework. I combine rigorous business analysis with rapid prototyping and system UX design.',
      learnMore: 'Learn more about our methodology →',
      steps: [
        {
          step: '01',
          title: '1. Understand Requirements',
          description: 'Deep dive into stakeholder goals, product discovery, and user needs to lay a solid foundation.',
        },
        {
          step: '02',
          title: '2. Analyze Business Logic',
          description: 'Synthesize requirements, business rules, entity models, and domain constraints.',
        },
        {
          step: '03',
          title: '3. Roles, Rules & States',
          description: 'Define RBAC permissions, validation rules, error handling, and comprehensive system states.',
        },
        {
          step: '04',
          title: '4. Flow & IA',
          description: 'Build user journeys, information architecture, navigation hierarchy, and cross-system workflows.',
        },
        {
          step: '05',
          title: '5. UI & Interaction',
          description: 'Craft high-fidelity interfaces, atomic design systems, and responsive layouts with pixel precision.',
        },
        {
          step: '06',
          title: '6. Prototype & Validate',
          description: 'Build interactive prototypes to stress-test real workflows, edge cases, and transaction paths.',
        },
        {
          step: '07',
          title: '7. Design QA',
          description: 'Audit layouts across breakpoints (1440px to 390px), ensuring design parity and accessibility.',
        },
        {
          step: '08',
          title: '8. Developer Handoff',
          description: 'Deliver structured Figma tokens, components, state specs, and support engineers during build.',
        },
      ],
    },
    portfolio: {
      badge: 'Portfolio',
      title: 'Featured Projects',
      subtitle: 'Explore 7 digital products spanning Vertical SaaS, travel booking, internal inventory operations, and omnichannel ticketing.',
      all: 'All',
      viewCaseStudy: 'View Case Study',
      seeCaseStudy: 'See Case Study',
      moreWork: 'View All Projects',
      client: 'Domain',
      year: 'Year',
      role: 'Role',
      platforms: 'Platforms',
      deliverables: 'Key Deliverables & System Logic',
      discussProject: 'Discuss Similar Project',
      close: 'Close',
      zoomIn: 'Click to expand image',
      closeZoom: 'Close full view',
      imageCounter: 'Screen',
      of: 'of',
      caseStudyNumber: 'Case Study',
      coreSkills: 'Core Design Skills & Domain',
      systemLogicTitle: 'System Logic & Architecture Highlights',
      modulesTitle: 'Operational Modules',
      modulesUnit: 'Modules',
      categories: {
        'All': 'All',
        'Vertical SaaS': 'Vertical SaaS',
        'Travel & Booking': 'Travel & Booking',
        'Internal Operations': 'Internal Operations',
        'Hybrid BA + UX': 'Hybrid BA + UX',
      },
    },
    cta: {
      badge: 'Product Design & System Strategy',
      title: 'Complex products need clear thinking.',
      titleHighlight: "Let's build impactful software together!",
      subtitle: 'I combine Business Analysis and Product Design to translate complex workflows, rules and system constraints into usable product experiences.',
      button: 'See My Process',
    },
    journey: {
      badge: 'CAREER JOURNEY',
      title: 'Career Journey',
      subtitle: 'Technical data foundation → Business Analysis → System Analysis → Product & UI/UX Design.',
      currentRoleTag: 'Current Role',
      items: [
        {
          yearBadge: '2023',
          stage: 'TECHNICAL DATA FOUNDATION',
          company: 'HPT Vietnam Corporation',
          role: 'Database Admin & Data Engineer Intern',
          period: '06/2023 – 09/2023',
          description: 'Built fundamentals in data structures, SQL queries, and backend technical constraints.',
          icon: 'Database',
          isCurrent: false,
        },
        {
          yearBadge: '2024–2025',
          stage: 'BUSINESS ANALYSIS FOUNDATION',
          company: 'IS Group',
          role: 'Business Analyst',
          period: '07/2024 – 02/2025',
          description: 'Analyzed customer requirements, mapped business rules, and authored functional specification documents.',
          icon: 'TrendingUp',
          isCurrent: false,
        },
        {
          yearBadge: '2025–2026',
          stage: 'SYSTEM & BUSINESS ANALYSIS',
          company: 'DOTB',
          role: 'Business Analyst — EdTech',
          period: '10/2025 – 01/2026',
          description: 'Analyzed EdTech product systems: commercial business rules, user permission matrix, validation, and operational flows.',
          icon: 'Cpu',
          isCurrent: false,
        },
        {
          yearBadge: '2026 – Present',
          stage: 'PRODUCT & UI/UX DESIGN',
          company: 'Techera',
          role: 'UIUX Designer / Product Designer',
          period: '02/2026 – Present',
          description: 'Leading product experience design: Information Architecture, multi-role SaaS, responsive web, native mobile, and Design QA.',
          icon: 'Sparkles',
          isCurrent: true,
        },
      ],
    },
    services: {
      badge: 'Value & Capabilities',
      title: 'I Bridge Business Logic with Product Experience',
      statement: 'I turn requirements and business logic into implementation-ready flows, states, and interfaces — aligning BA, Product, Design, Dev, and QA around a unified product logic.',
      process: ['Requirement', 'Logic', 'Flow', 'UI', 'Handoff'],
      sayHello: 'Discuss Collaboration',
      card1: {
        number: '01',
        title: 'Product & UI/UX Design',
        subtitle: 'From product structure to implementation-ready interaction.',
        skills: [
          'Information Architecture',
          'User Flow & Journey Mapping',
          'Interaction Design',
          'Responsive Web / Mobile',
          'Admin & SaaS UX',
          'Design System',
          'Components & UI States',
          'Interactive Prototyping',
          'Design Specification',
          'Handoff & Design QA',
        ],
      },
      card2: {
        number: '02',
        title: 'Business Analysis & System Thinking',
        subtitle: 'Turning business requirements into structured product logic.',
        skills: [
          'Requirement Analysis & Clarification',
          'Feature Breakdown',
          'Business Rules',
          'Roles & Permissions',
          'Use Case / User Story / Acceptance Criteria',
          'AS-IS / TO-BE',
          'Fields & Data Mapping',
          'Validation Rules',
          'System States',
          'Edge Cases & Exception Flows',
          'UAT Support',
        ],
      },
      card3: {
        number: '03',
        title: 'Tools & Workflow',
        primaryToolTitle: 'PRIMARY DESIGN TOOL',
        figmaCaption: 'Auto Layout · Components · Variables · Prototyping',
        analysisToolsTitle: 'ANALYSIS / DELIVERY TOOLS',
        aiWorkflowTitle: 'AI-ASSISTED WORKFLOW',
        aiScope: 'Requirement review · Edge-case discovery · Flow/IA exploration · Design review · Documentation',
        aiMicroNote: 'AI supports production; product logic and UX decisions remain designer-controlled.',
      },
      howIWork: {
        title: 'HOW I WORK',
        items: [
          'Stakeholder Communication',
          'Requirement Clarification',
          'Cross-functional Collaboration',
          'Structured Problem Solving',
          'Ownership & Proactivity',
          'Attention to Detail',
          'Product Trade-off Thinking',
        ],
      },
    },
    contact: {
      badge: 'Get in Touch',
      title: "Let's build clearer digital products.",
      subtitle: "I'm open to Business Analyst, UI/UX Designer and system-oriented product opportunities.",
      addressTitle: 'Location',
      addressValue: 'Ho Chi Minh City, Vietnam',
      emailTitle: 'Email',
      phoneTitle: 'Phone Number',
      phoneValue: 'Available upon request / Zalo',
      phoneNote: 'Ready for direct call or Zalo discussion',
      cvDownloadsTitle: 'Download Specialized Resumes (CV)',
      cvDownloadsSubtitle: 'Select and download the resume version suited to your role requirements',
      cvPdfsReady: '3 PDF Tracks Ready',
      downloadPdf: 'Download PDF',
      budgetOption1: 'Full-time Employment',
      budgetOption2: 'Contract / Freelance Project',
      budgetOption3: 'Design System & QA Consulting',
      budgetOption4: 'Other Inquiries',
      cvList: [
        {
          id: 'uiux',
          role: 'UI/UX Designer',
          specialty: 'Product Design, Design System, Complex Workflows',
          fileName: 'Nguyen_Xuan_Hau_CV_UIUX_Designer.pdf',
          badge: 'Design Track',
        },
        {
          id: 'ba',
          role: 'Business Analyst (BA)',
          specialty: 'Requirements, System Rules, RBAC & Data Logic',
          fileName: 'Nguyen_Xuan_Hau_CV_Business_Analyst.pdf',
          badge: 'BA Track',
        },
        {
          id: 'tech',
          role: 'Computer Engineering & Tech',
          specialty: 'Database Architecture, SQL Queries, Tech Fundamentals',
          fileName: 'Nguyen_Xuan_Hau_CV_Computer_Engineering.pdf',
          badge: 'Tech Track',
        },
      ],
      followMe: 'Connect with me',
      yourName: 'Your Name *',
      yourEmail: 'Your Email *',
      subject: 'Discussion Topic',
      budget: 'Opportunity Type',
      message: 'Your Message *',
      send: 'Send Message',
      sending: 'Sending message...',
      successTitle: 'Message Sent Successfully!',
      successDesc: "Thank you for reaching out. I'll review your inquiry and respond within 24 hours.",
    },
    footer: {
      rights: 'All rights reserved.',
    },
  },
  vi: {
    nav: {
      home: 'Trang chủ',
      about: 'Giới thiệu',
      process: 'Quy trình',
      portfolio: 'Dự án',
      journey: 'Lộ trình & Quy trình',
      services: 'Kỹ năng',
      contact: 'Liên hệ',
      hireMe: 'Liên hệ ngay',
      langToggle: 'EN',
    },
    hero: {
      eyebrow: 'BUSINESS ANALYST · UI/UX DESIGNER',
      badge: 'BUSINESS ANALYST · UI/UX DESIGNER',
      greeting: 'Xin chào, tôi là',
      name: 'Nguyễn Xuân Hậu',
      role: 'Business Analyst & UI/UX Designer',
      mainDesc: 'Tôi kết nối yêu cầu nghiệp vụ với trải nghiệm người dùng — chuyển hóa các luồng quy trình, quy tắc và logic hệ thống phức tạp thành các giao diện rõ ràng, thực tế trên các nền tảng Web, Mobile và Admin.',
      personalIntro: 'Tôi khởi đầu sự nghiệp từ Business Analysis, làm việc với yêu cầu, luồng nghiệp vụ và logic hệ thống trước khi chuyển sâu hơn vào UI/UX. Nền tảng đó định hình cách tôi thiết kế hiện tại: Tôi ưu tiên thấu hiểu cách sản phẩm vận hành trước khi quyết định giao diện và tương tác của nó.',
      subtitle: 'Tôi kết nối yêu cầu nghiệp vụ với trải nghiệm người dùng — chuyển hóa các luồng quy trình, quy tắc và logic hệ thống phức tạp thành các giao diện rõ ràng, thực tế trên các nền tảng Web, Mobile và Admin.',
      sayHello: 'Liên hệ ngay',
      viewPortfolio: 'Xem dự án',
      specialty: 'Chuyên môn',
      specialtyTitle: 'Business Analysis & UI/UX',
      stats: [
        { value: 'BA → UX', label: 'Từ nghiệp vụ đến giao diện' },
        { value: '7 Dự án', label: 'Hệ thống sản phẩm thực tế' },
        { value: 'Web · Mobile · Admin', label: 'Kinh nghiệm đa nền tảng' },
      ],
    },
    about: {
      eyebrow: 'CÁCH TÔI TƯ DUY',
      titlePart1: 'Nơi Business Logic Trở Thành',
      titlePart2: 'Product Experience',
      statement: 'Nền tảng Business Analysis giúp tôi nhìn sản phẩm từ requirement, quy tắc nghiệp vụ, trạng thái và edge case trước khi đi vào giao diện. Khi chuyển sang UI/UX, tôi dùng nền tảng đó để biến logic hệ thống thành những luồng rõ ràng, dễ sử dụng và có thể bàn giao để triển khai.',
      pipeline: {
        tag: 'DÒNG CHẢY CHUYỂN HÓA HỆ THỐNG',
        steps: ['Business Requirement', 'Product Logic', 'UX Flow', 'Interface'],
      },
      business: {
        tag: 'TẦNG ĐẦU VÀO · TƯ DUY HỆ THỐNG',
        title: 'BUSINESS LOGIC',
        subtitle: 'Nền tảng nghiệp vụ & Ràng buộc hệ thống',
        items: [
          { num: '01', name: 'Requirement', desc: 'Mục tiêu kinh doanh, bài toán người dùng & phạm vi hệ thống' },
          { num: '02', name: 'Business Rules', desc: 'Quy tắc vận hành, điều kiện ràng buộc & logic kích hoạt' },
          { num: '03', name: 'Roles & Permissions', desc: 'Phân quyền ma trận người dùng (RBAC) & ranh giới tác vụ' },
          { num: '04', name: 'Fields & Validation', desc: 'Cấu trúc dữ liệu, ràng buộc trường & luật kiểm tra lỗi' },
          { num: '05', name: 'System States', desc: 'Vòng đời dữ liệu, đồng bộ & chuyển đổi trạng thái nền' },
          { num: '06', name: 'Edge Cases', desc: 'Tình huống ngoại lệ, lỗi mạng & xử lý bất thường phát sinh' },
        ],
      },
      bridge: {
        badge: 'BA → UX',
        title: 'CẦU NỐI',
        steps: [
          { step: '01', name: 'UNDERSTAND', desc: 'Thấu hiểu logic & ràng buộc' },
          { step: '02', name: 'STRUCTURE', desc: 'Cấu trúc hóa dữ liệu & luồng' },
          { step: '03', name: 'TRANSLATE', desc: 'Chuyển hóa giao diện & trải nghiệm' },
        ],
      },
      experience: {
        tag: 'TẦNG ĐẦU RA · THIẾT KẾ TRẢI NGHIỆM',
        title: 'PRODUCT EXPERIENCE',
        subtitle: 'Trải nghiệm tương tác, giao diện số & Design QA',
        items: [
          { num: '01', name: 'Information Architecture', desc: 'Cấu trúc phân tầng & sơ đồ điều hướng thông tin rõ ràng' },
          { num: '02', name: 'User Flow', desc: 'Luồng thao tác tinh gọn, triệt tiêu điểm nghẽn & ma sát' },
          { num: '03', name: 'Interaction Design', desc: 'Phản hồi vi mô, tương tác trực quan & chuyển cảnh mượt mà' },
          { num: '04', name: 'UI States & Feedback', desc: 'Thiết kế trọn vẹn Empty, Loading, Validation, Error & Success' },
          { num: '05', name: 'Responsive Interface', desc: 'Thích ứng hoàn hảo Desktop, Tablet & Mobile đa kích thước' },
          { num: '06', name: 'Design QA', desc: 'Kiểm thử độ chính xác giao diện & bàn giao thông số kỹ thuật dev' },
        ],
      },
      principlesTitle: 'NGUYÊN TẮC THIẾT KẾ',
      principles: [
        {
          num: '01',
          title: 'LOGIC BEFORE PIXELS',
          quote: '“Làm rõ requirement, rule và dependency trước khi quyết định giao diện.”',
        },
        {
          num: '02',
          title: 'DESIGN THE STATE, NOT ONLY THE HAPPY PATH',
          quote: '“Empty, loading, validation, permission và exception đều là một phần của trải nghiệm.”',
        },
        {
          num: '03',
          title: 'CLARIFY BEFORE ASSUMING',
          quote: '“Khi requirement chưa rõ, ưu tiên trao đổi với BA, PM, Developer và QA thay vì tự suy diễn.”',
        },
      ],
      beyond: {
        badge: 'BEYOND PRODUCT',
        desc: 'Ngoài product design, tôi quan tâm đến AI-assisted workflow, phần cứng, in 3D và cách các hệ thống kỹ thuật vận hành.',
        tags: ['AI-assisted Workflow', '3D Printing', 'Hardware', 'New Technology'],
      },
      // Fallbacks
      badge: 'CÁCH TÔI TƯ DUY',
      role: 'Nơi Business Logic Trở Thành Product Experience',
    },
    process: {
      badge: 'Quy trình',
      title: 'Quy Trình Làm Việc',
      subtitle: 'Mỗi dự án đều tuân theo khung thiết kế lấy con người làm trung tâm, kết hợp chặt chẽ giữa phân tích nghiệp vụ, kiến trúc thông tin và thiết kế giao diện.',
      learnMore: 'Tìm hiểu thêm về phương pháp luận →',
      steps: [
        {
          step: '01',
          title: '1. Thấu hiểu yêu cầu',
          description: 'Nghiên cứu mục tiêu kinh doanh, phân tích bối cảnh bài toán và nhu cầu người dùng làm nền móng vững chắc.',
        },
        {
          step: '02',
          title: '2. Phân tích logic nghiệp vụ',
          description: 'Bóc tách quy tắc nghiệp vụ, mô hình thực thể dữ liệu và các ràng buộc hệ thống trước khi vẽ màn hình.',
        },
        {
          step: '03',
          title: '3. Vai trò, quy tắc & trạng thái',
          description: 'Xác định phân quyền vai trò (RBAC), kiểm tra tính hợp lệ dữ liệu, xử lý ngoại lệ và trạng thái tương tác.',
        },
        {
          step: '04',
          title: '4. Xây dựng luồng & IA',
          description: 'Kiến trúc hóa hành trình người dùng, phân cấp điều hướng và luồng xử lý liên hệ thống xuyên suốt.',
        },
        {
          step: '05',
          title: '5. Thiết kế UI & tương tác',
          description: 'Thiết kế giao diện độ nét cao, hệ thống Design System nguyên tử và layout responsive chuẩn xác.',
        },
        {
          step: '06',
          title: '6. Prototype & kiểm thử',
          description: 'Tạo bản mẫu tương tác thực tế để kiểm tra giao dịch, các trường hợp biên và mật độ dữ liệu.',
        },
        {
          step: '07',
          title: '7. Kiểm thử thiết kế (QA)',
          description: 'Đánh giá độ tương thích trên các độ phân giải (1440px đến 390px), đảm bảo chuẩn UX nhất quán.',
        },
        {
          step: '08',
          title: '8. Bàn giao lập trình (Handoff)',
          description: 'Cung cấp Figma tokens, components chuẩn xác, tài liệu chi tiết và đồng hành cùng team Developer.',
        },
      ],
    },
    portfolio: {
      badge: 'Dự án',
      title: 'Dự Án Tiêu Biểu',
      subtitle: 'Khám phá 7 sản phẩm số thực tế trải dài từ Vertical SaaS, cổng đặt vé du lịch, kho vận nội bộ đến hệ sinh thái đa kênh.',
      all: 'Tất cả',
      viewCaseStudy: 'Xem chi tiết',
      seeCaseStudy: 'Xem chi tiết',
      moreWork: 'Xem tất cả 7 dự án',
      client: 'Lĩnh vực',
      year: 'Năm',
      role: 'Vai trò',
      platforms: 'Nền tảng',
      deliverables: 'Hạng mục bàn giao & Logic hệ thống',
      discussProject: 'Thảo luận về dự án này',
      close: 'Đóng',
      zoomIn: 'Bấm để xem ảnh phóng to',
      closeZoom: 'Đóng chế độ phóng to',
      imageCounter: 'Hình',
      of: 'trên',
      caseStudyNumber: 'Hồ sơ dự án',
      coreSkills: 'Lĩnh Vực & Kỹ Năng Thiết Kế Cốt Lõi',
      systemLogicTitle: 'Điểm Sáng Logic Hệ Thống & Kiến Trúc',
      modulesTitle: 'Phân Hệ Chức Năng',
      modulesUnit: 'Phân hệ',
      categories: {
        'All': 'Tất cả',
        'Vertical SaaS': 'Vertical SaaS',
        'Travel & Booking': 'Du lịch & Đặt vé',
        'Internal Operations': 'Vận hành nội bộ',
        'Hybrid BA + UX': 'Kết hợp BA + UX',
      },
    },
    cta: {
      badge: 'Thiết Kế Sản Phẩm & Tư Duy Hệ Thống',
      title: 'Sản phẩm phức tạp cần tư duy rõ ràng.',
      titleHighlight: 'Cùng trao đổi về sản phẩm của bạn!',
      subtitle: 'Tôi kết hợp tư duy Business Analysis và Product Design để chuyển hóa các luồng nghiệp vụ, quy tắc và ràng buộc hệ thống thành trải nghiệm người dùng tối ưu.',
      button: 'Xem quy trình làm việc',
    },
    journey: {
      badge: 'HÀNH TRÌNH SỰ NGHIỆP',
      title: 'Lộ Trình Nghề Nghiệp',
      subtitle: 'Nền tảng kỹ thuật dữ liệu → Business Analysis → Phân tích hệ thống → Thiết kế Sản phẩm & UI/UX.',
      currentRoleTag: 'Vị trí hiện tại',
      items: [
        {
          yearBadge: '2023',
          stage: 'NỀN TẢNG KỸ THUẬT DỮ LIỆU',
          company: 'HPT Vietnam Corporation',
          role: 'Thực tập sinh Quản trị CSDL & Kỹ sư Dữ liệu',
          period: '06/2023 – 09/2023',
          description: 'Xây dựng tư duy cấu trúc dữ liệu, câu lệnh truy vấn và các ràng buộc kỹ thuật của backend.',
          icon: 'Database',
          isCurrent: false,
        },
        {
          yearBadge: '2024–2025',
          stage: 'NỀN TẢNG PHÂN TÍCH NGHIỆP VỤ',
          company: 'IS Group',
          role: 'Business Analyst',
          period: '07/2024 – 02/2025',
          description: 'Phân tích yêu cầu khách hàng, xác định các trường hợp nghiệp vụ và lập tài liệu đặc tả chức năng.',
          icon: 'TrendingUp',
          isCurrent: false,
        },
        {
          yearBadge: '2025–2026',
          stage: 'PHÂN TÍCH HỆ THỐNG & NGHIỆP VỤ',
          company: 'DOTB',
          role: 'Business Analyst — EdTech',
          period: '10/2025 – 01/2026',
          description: 'Phân tích hệ thống sản phẩm giáo dục: quy tắc kinh doanh, phân quyền tài khoản, validation và luồng thao tác.',
          icon: 'Cpu',
          isCurrent: false,
        },
        {
          yearBadge: '2026 – Hiện tại',
          stage: 'THIẾT KẾ SẢN PHẨM & UI/UX',
          company: 'Techera',
          role: 'UIUX Designer / Product Designer',
          period: '02/2026 – Hiện tại',
          description: 'Phụ trách thiết kế trải nghiệm sản phẩm: Kiến trúc thông tin, SaaS đa phân quyền, Responsive Web và Mobile App.',
          icon: 'Sparkles',
          isCurrent: true,
        },
      ],
    },
    services: {
      badge: 'Giá trị & Kỹ năng',
      title: 'Tôi Kết Nối Business Logic Với Product Experience',
      statement: 'Tôi chuyển requirement và business logic thành flow, state và giao diện có thể triển khai — đồng thời kết nối BA, Product, Design, Dev và QA trong cùng một logic sản phẩm.',
      process: ['Requirement', 'Logic', 'Flow', 'UI', 'Handoff'],
      sayHello: 'Liên hệ trao đổi',
      card1: {
        number: '01',
        title: 'Product & UI/UX Design',
        subtitle: 'Từ cấu trúc sản phẩm đến tương tác sẵn sàng triển khai.',
        skills: [
          'Information Architecture',
          'User Flow & Journey Mapping',
          'Interaction Design',
          'Responsive Web / Mobile',
          'Admin & SaaS UX',
          'Design System',
          'Components & UI States',
          'Interactive Prototyping',
          'Design Specification',
          'Handoff & Design QA',
        ],
      },
      card2: {
        number: '02',
        title: 'Business Analysis & System Thinking',
        subtitle: 'Chuyển hóa bài toán kinh doanh thành logic sản phẩm có cấu trúc.',
        skills: [
          'Requirement Analysis & Clarification',
          'Feature Breakdown',
          'Business Rules',
          'Roles & Permissions',
          'Use Case / User Story / Acceptance Criteria',
          'AS-IS / TO-BE',
          'Fields & Data Mapping',
          'Validation Rules',
          'System States',
          'Edge Cases & Exception Flows',
          'UAT Support',
        ],
      },
      card3: {
        number: '03',
        title: 'Tools & Workflow',
        primaryToolTitle: 'CÔNG CỤ THIẾT KẾ CHÍNH',
        figmaCaption: 'Auto Layout · Components · Variables · Prototyping',
        analysisToolsTitle: 'CÔNG CỤ PHÂN TÍCH & BÀN GIAO',
        aiWorkflowTitle: 'QUY TRÌNH HỖ TRỢ VỚI AI',
        aiScope: 'Rà soát requirement · Phát hiện edge-case · Thăm dò luồng/IA · Kiểm tra thiết kế · Tài liệu hóa',
        aiMicroNote: 'AI hỗ trợ tăng tốc quy trình; logic sản phẩm và quyết định UX vẫn do designer trực tiếp kiểm soát.',
      },
      howIWork: {
        title: 'CÁCH TÔI LÀM VIỆC',
        items: [
          'Stakeholder Communication',
          'Requirement Clarification',
          'Cross-functional Collaboration',
          'Structured Problem Solving',
          'Ownership & Proactivity',
          'Attention to Detail',
          'Product Trade-off Thinking',
        ],
      },
    },
    contact: {
      badge: 'LIÊN HỆ',
      title: 'Cùng xây dựng các sản phẩm số trực quan hơn.',
      subtitle: 'Tôi sẵn sàng đón nhận cơ hội ở các vị trí Business Analyst, UI/UX Designer và các dự án sản phẩm số định hướng hệ thống.',
      addressTitle: 'ĐỊA ĐIỂM',
      addressValue: 'Thành phố Hồ Chí Minh, Việt Nam',
      emailTitle: 'EMAIL',
      phoneTitle: 'SỐ ĐIỆN THOẠI',
      phoneValue: 'Sẵn sàng kết nối qua SĐT / Zalo',
      phoneNote: 'Sẵn sàng trao đổi trực tiếp',
      cvDownloadsTitle: 'Tải Hồ Sơ Năng Lực (CV)',
      cvDownloadsSubtitle: 'Chọn và tải phiên bản hồ sơ năng lực phù hợp với tiêu chí tuyển dụng của bạn',
      cvPdfsReady: '3 File PDF Sẵn Sàng',
      downloadPdf: 'Tải xuống bản PDF',
      budgetOption1: 'Toàn thời gian (Full-time)',
      budgetOption2: 'Dự án / Hợp đồng (Contract/Freelance)',
      budgetOption3: 'Tư vấn Design System & Kiểm thử QA',
      budgetOption4: 'Trao đổi khác',
      cvList: [
        {
          id: 'uiux',
          role: 'CV UI/UX Designer',
          specialty: 'Thiết kế Sản phẩm, Design System, SaaS Đa Phân Quyền',
          fileName: 'Nguyen_Xuan_Hau_CV_UIUX_Designer.pdf',
          badge: 'Chuyên môn UI/UX',
        },
        {
          id: 'ba',
          role: 'CV Business Analyst (BA)',
          specialty: 'Đặc tả yêu cầu, Logic nghiệp vụ, RBAC, Luồng tương tác',
          fileName: 'Nguyen_Xuan_Hau_CV_Business_Analyst.pdf',
          badge: 'Chuyên môn BA',
        },
        {
          id: 'tech',
          role: 'CV Kỹ thuật Máy tính / IT',
          specialty: 'Kiến trúc CSDL, Truy vấn SQL, Tư duy kỹ thuật hệ thống',
          fileName: 'Nguyen_Xuan_Hau_CV_Computer_Engineering.pdf',
          badge: 'Kỹ thuật & Dữ liệu',
        },
      ],
      followMe: 'KẾT NỐI CÙNG TÔI',
      yourName: 'Họ và tên của bạn *',
      yourEmail: 'Địa chỉ Email *',
      subject: 'Chủ đề trao đổi',
      budget: 'Loại hình cơ hội',
      message: 'Nội dung lời nhắn *',
      send: 'Gửi tin nhắn',
      sending: 'Đang gửi tin nhắn...',
      successTitle: 'Đã gửi tin nhắn thành công!',
      successDesc: 'Cảm ơn bạn đã liên hệ. Tôi sẽ phản hồi lại bạn trong vòng 24 giờ.',
    },
    footer: {
      rights: 'Bảo lưu mọi quyền.',
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('portfolio_lang') || 'vi';
  });

  useEffect(() => {
    localStorage.setItem('portfolio_lang', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'vi' : 'en'));
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
